services:
  bot:
    build: .
    container_name: karusel_bot_new
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  exports:
    image: nginx:alpine
    container_name: karusel_exports_new
    restart: always
    ports:
      - "127.0.0.1:8082:80"
    volumes:
      - ./data/exports:/usr/share/nginx/html:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
